name: zoom-drive-connector
dependencies:
  - python=3.6
  - pyyaml=3.12
  - nose=1.3.7 # Dev dependency.
  - pip:
      - mypy==0.641  # Dev dependency.
      - pycodestyle==2.4.0 # Dev dependency.
      - pylint==1.9.2 # Dev dependency.
      - responses==0.10.2 # Dev dependency.
      - schedule==0.5.0
      - google-api-python-client==1.6.7
      - oauth2client==4.1.2
      - httplib2shim==0.0.3
      - slackclient==1.2.1
      - pyjwt==1.5.3
